apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.global.secrets.dbPassword | quote }}
  SECRET_KEY: {{ .Values.global.secrets.secretKey | quote }}
  JWT_SECRET: {{ .Values.global.secrets.jwtSecret | quote }}
