image:
  repository: mysql
  tag: "8.0"
rootPassword: ""
database: saista_bakers
storage:
  size: 5Gi
  nfsServer: "172.31.12.241"
  nfsPath: "/exports/saista/mysql"
gateway:
  name: saista-gateway
  controllerName: kgateway.dev/kgateway
