apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
