replicaCount: 2
image:
  repository: asadoblivion/saista-order-service
  pullPolicy: Always
port: 5002
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
