global:
  namespace: prod
  imageTag: latest

mysql:
  gateway:
    name: saista-gateway-prod       # separate Gateway for prod namespace
    createClass: false              # GatewayClass already exists from dev install; don't recreate
  storage:
    createStorageClass: false       # StorageClass already exists from dev install; don't recreate

user-service:
  replicaCount: 2

order-service:
  replicaCount: 2

payment-service:
  replicaCount: 2

frontend:
  replicaCount: 2
